import { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Dona Getta - Login',
  description: 'Generated by create next app',
}

export default function LoginLayout({ children }: { children: ReactNode }) {
  return <div className="pt-4">{children}</div>
}
